version: '2.1'

services:
  web:
    image: flask_cut
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data:/data
    ports:
      - 27017:27017
    command: mongod --smallfiles # --quiet 
